name: air_quality_waqi
description: Air quality index from the World's Air Quality Index (WAQI) service.
version: 1.0.0
homepage: https://github.com/Ziut3k-dev/air_quality-WAQI-API-
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: