name: Codecov
on:
  push:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          with:
            files: coverage/lcov.info 
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    